deployment:
  tasks:
    - export DEPLOYPATH=/home/CPANEL_USER/public_html/
    - cd /home/CPANEL_USER/repos/my-react-app
    - npm install
    - npm run build
 - /bin/rsync -av --delete dist/ $DEPLOYPATH
